name: Update Snake

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: jaywcjlove/snake@main
        with:
          # Your GitHub username
          github_user_name: arafat22184
          # Output file path
          svg_file_path: dist/github-contribution-grid-snake.svg

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation"
          branch: main
          file_pattern: dist/github-contribution-grid-snake.svg